version: '3'
services:
  backend:
    build: ./pokemon-battle-backend # โฟลเดอร์ backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=13.228.191.168  # IP ของ EC2 instance ที่รัน PostgreSQL
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=vkiydKN8825  # รหัสผ่านของ PostgreSQL ที่คุณตั้งไว้
      - DB_NAME=postgres

  frontend:
    build: ./pokemon_battle_front # โฟลเดอร์ frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
